FROM maven:3.8.3-amazoncorretto-17 AS build
RUN mkdir /code && chown 185 /code
WORKDIR /code
COPY  --chown=185 .mvn /code/.mvn
COPY --chown=185 pom.xml /code/
COPY --chown=185 mvnw /code/
COPY --chown=185 src /code/src
USER 185

RUN mvn package

FROM amazoncorretto:17

RUN mkdir /deployments && mkdir /deployments/lib
COPY --chown=185 --from=build /code/target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 --from=build /code/target/quarkus-app/*.jar /deployments/
COPY --chown=185 --from=build /code/target/quarkus-app/app/ /deployments/app/
COPY --chown=185 --from=build /code/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-p /deployments/lib/:/deployments/ -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT /bin/java  ${JAVA_OPTS} "-jar"  ${JAVA_APP_JAR}  